// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqc4cYhap6hW450bNvl0UDkgZdAaEO8k',
    appId: '1:518634998629:web:7454b48686a4aae2d96f8c',
    messagingSenderId: '518634998629',
    projectId: 'detalles-8f51f',
    authDomain: 'detalles-8f51f.firebaseapp.com',
    databaseURL: 'https://detalles-8f51f-default-rtdb.firebaseio.com',
    storageBucket: 'detalles-8f51f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxy6_-zOn--0eKoAX3ag7mo0ih4qGoEyc',
    appId: '1:518634998629:android:98738ea899f1a037d96f8c',
    messagingSenderId: '518634998629',
    projectId: 'detalles-8f51f',
    databaseURL: 'https://detalles-8f51f-default-rtdb.firebaseio.com',
    storageBucket: 'detalles-8f51f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE4M4aC2C52lE_F-Sr61bNwTcJ728VCm4',
    appId: '1:518634998629:ios:af197e81666043acd96f8c',
    messagingSenderId: '518634998629',
    projectId: 'detalles-8f51f',
    databaseURL: 'https://detalles-8f51f-default-rtdb.firebaseio.com',
    storageBucket: 'detalles-8f51f.appspot.com',
    androidClientId: '518634998629-gi808vtb133qpcnh6amhb4sr95jruuql.apps.googleusercontent.com',
    iosClientId: '518634998629-pto2rcpc8gpi19fdkq5h685u5273ii9a.apps.googleusercontent.com',
    iosBundleId: 'com.alexgoga120.accesoMovilidad',
  );
}
